networks:
  default:
    name: transcendence
    external: false



services:
  gateway:
    container_name: gateway
    build: ./gateway
    ports:
      - "8000:8000"
    volumes:
      - ${LOGSTASH_FOLDER}${GATEWAY_LOG}:/var/log/${GATEWAY_LOG}
    env_file:
      - .env

  usermanagement:
    container_name: usermanagement
    build: ./usermanagement
    volumes:
      - ${LOGSTASH_FOLDER}${USER_LOG}:/var/log/${USER_LOG}
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@db:5432/mydatabase

  chat:
    container_name: chat
    build: ./chat
    volumes:
      - ${LOGSTASH_FOLDER}${CHAT_LOG}:/var/log/${CHAT_LOG}
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@db:5432/mydatabase

  gamestats:
    container_name: gamestats
    build: ./gamestats
    volumes:
      - ${LOGSTASH_FOLDER}${GAMESTATS_LOG}:/var/log/${GAMESTATS_LOG}
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@db:5432/mydatabase

  twofactor:
    container_name: twofactor
    build: ./twofactor
    volumes:
      - ${LOGSTASH_FOLDER}${TWOFACTOR_LOG}:/var/log/${TWOFACTOR_LOG}
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@db:5432/mydatabase

  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
  grafana:
    image: grafana/grafana:11.1.1-ubuntu
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana


  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - ./ELK/setup_script.sh:/setup_script.sh
      - ./ELK/gateway_index.ndjson:/gateway_index.ndjson
      - ./ELK/gateway_dashboard.ndjson:/gateway_dashboard.ndjson

    user: "0"
    env_file:
      - .env
    command: >
      bash /setup_script.sh
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120

  es01:
    depends_on:
      setup:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    labels:
      co.elastic.logs/module: elasticsearch
    container_name: elasticsearch
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata01:/usr/share/elasticsearch/data
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  logstash:
    depends_on:
      es01:
        condition: service_healthy
      kibana:
        condition: service_healthy
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    labels:
      co.elastic.logs/module: logstash
    container_name: logstash
    user: root

    volumes:
      - certs:/usr/share/logstash/certs
      - ./logstash:/usr/share/logstash/pipeline:ro
      - logstashdata01:/var/log
    environment:
      - xpack.monitoring.enabled=false
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://es01:9200
    env_file:
      - .env

  kibana:
    depends_on:
      es01:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    labels:
      co.elastic.logs/module: kibana
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data

    container_name: kibana
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - XPACK_SECURITY_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_REPORTING_ENCRYPTIONKEY=${ENCRYPTION_KEY}
    ports:
      - ${KIBANA_PORT}:5601
    mem_limit: ${KB_MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120



volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      device: ${CERTS_FOLDER}
      o: bind
  esdata01:
    driver: local
    driver_opts:
      type: none
      device: ${ESDATA_FOLDER}
      o: bind
  kibanadata:
    driver: local
    driver_opts:
      type: none
      device: ${KIBANA_FOLDER}
      o: bind
  logstashdata01:
    driver: local
    driver_opts:
      type: none
      device: ${LOGSTASH_FOLDER}
      o: bind
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ${POSTGREE_FOLDER}
      o: bind
  prometheus-data:
    driver: local
    driver_opts:
      type: none
      device: ${PROMETHEUS_FOLDER}
      o: bind
  grafana-data:
    driver: local
    driver_opts:
      type: none
      device: ${GRAFANA_FOLDER}
      o: bind
