global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'gateway'
    scrape_interval: 5s
    static_configs:
      - targets: ['gateway:8000']

  - job_name: 'blockchain'
    scrape_interval: 5s
    static_configs:
      - targets: ['blockchain:8000']

  - job_name: 'chat'
    scrape_interval: 5s
    static_configs:
      - targets: ['chat:8000']

  - job_name: 'gamestats'
    scrape_interval: 5s
    static_configs:
      - targets: ['gamestats:8000']

  - job_name: 'twofactor'
    scrape_interval: 5s
    static_configs:
      - targets: ['twofactor:8000']

  - job_name: 'usermanagement'
    scrape_interval: 5s
    static_configs:
      - targets: ['usermanagement:8000']

  - job_name: 'docker'
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9323"]