services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - userservice
      - chatservice

  userservice:
    build: ./userservice
    ports:
      - "8001:8000"
    volumes:
      - userservice-data:/app

  chatservice:
    build: ./chatservice
    ports:
      - "8002:8000"
    volumes:
      - chatservice-data:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  userservice-data:
  chatservice-data:
