volumes:
  certs:
    driver: local
  esdata01:
    driver: local
  kibanadata:
    driver: local
  metricbeatdata01:
    driver: local
  filebeatdata01:
    driver: local
  logstashdata01:
    driver: local
  postgres-data:
  userservice-data:
  chatservice-data:
  es-data:


networks:
  elk:
    driver: 
      bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.9
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - logstashdata01:/var/log
    ports:
      - "5044:5044"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - userservice
      - chatservice
    volumes:
      - logstashdata01:/var/log
    networks:
      - elk

  userservice:
    build: ./userservice
    ports:
      - "8001:8000"
    volumes:
      - userservice-data:/app
    networks:
      - elk
  chatservice:
    build: ./chatservice
    ports:
      - "8002:8000"
    volumes:
      - chatservice-data:/app
    networks:
      - elk  
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - elk



