global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['gateway:8000']
  - job_name: 'user'
    scrape_interval: 5s
    static_configs:
      - targets: ['userservice:8001']